### ISSUE TITLE
開発環境でtraQ-Rが起動していない

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/traQ#416]
```
(Error 1062: Duplicate entry '039d4504-232d-488f-bb35-0744f06225b7-d82c2662-1296-4b6c-b2be-68e' for key 'PRIMARY')
[2019-02-15 08:31:56]
{"time":"2019-02-15T08:31:56.627921988Z","level":"ERROR","prefix":"echo","file":"notification.go","line":"76","message":"Error 1062: Duplicate entry '039d4504-232d-488f-bb35-0744f06225b7-d82c2662-1296-4b6c-b2be-68e' for key 'PRIMARY'"}
{"time":"2019-02-15T08:31:57.694226924Z","level":"ERROR","prefix":"echo","file":"notification.go","line":"76","message":"Error 1062: Duplicate entry '039d4504-232d-488f-bb35-0744f06225b7-d82c2662-1296-4b6c-b2be-68e' for key 'PRIMARY'"}

(Error 1062: Duplicate entry '039d4504-232d-488f-bb35-0744f06225b7-d82c2662-1296-4b6c-b2be-68e' for key 'PRIMARY')
[2019-02-15 08:31:57]
panic: interface conversion: interface {} is nil, not uuid.UUID

goroutine 99 [running]:
github.com/traPtitech/traQ/router.(*SSEStreamer).processUserMulticastEvent(0xc0004bd040, 0xe22457, 0xc, 0x0, 0x0, 0x0, 0xc0004667b0)
	/go/src/github.com/traPtitech/traQ/router/server_sent_events.go:421 +0x2710
created by github.com/traPtitech/traQ/router.(*SSEStreamer).setupSubscriber.func4
	/go/src/github.com/traPtitech/traQ/router/server_sent_events.go:186 +0xe1
```

**Comment by tohutohu** [comment]
エラー箇所
https://github.com/traPtitech/traQ/blob/master/router/server_sent_events.go#L421
