### ISSUE TITLE
CreateStampPaletteハンドラで`field #2 cannot be found in the struct`が発生する

### ISSUE THREAD

**Issue by wtks** [traPtitech/traQ#918]
```
field #2 cannot be found in the struct
goroutine 11110643 [running]:
runtime/debug.Stack(0xc004898ae0, 0xc005388400, 0xc00409cef8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/traPtitech/traQ/router/extension/herror.InternalServerError(0x144afa0, 0xc002c0c248, 0xc002c0c248, 0x1457fa0)
	/go/src/github.com/traPtitech/traQ/router/extension/herror/500.go:33 +0x37
github.com/traPtitech/traQ/router/extension.BindAndValidate(0x1486b20, 0xc00b2ebf70, 0x10a0840, 0xc005388380, 0x115bfc0, 0xc000995020)
	/go/src/github.com/traPtitech/traQ/router/extension/context.go:68 +0x1e5
github.com/traPtitech/traQ/router/v3.bindAndValidate(...)
	/go/src/github.com/traPtitech/traQ/router/v3/utils.go:26
github.com/traPtitech/traQ/router/v3.(*Handlers).CreateStampPalette(0xc000264ab0, 0x1486b20, 0xc00b2ebf70, 0x121ae01, 0x147b720)
	/go/src/github.com/traPtitech/traQ/router/v3/stamp_palettes.go:48 +0xa3
github.com/traPtitech/traQ/router/middlewares.AccessControlMiddlewareGenerator.func1.1.1(0x1486b20, 0xc00b2ebf70, 0xc006619bc0, 0x147b720)
	/go/src/github.com/traPtitech/traQ/router/middlewares/access_control.go:40 +0x2a9
github.com/traPtitech/traQ/router/middlewares.BlockBot.func1.1(0x1486b20, 0xc00b2ebf70, 0x1046820, 0x1426080)
	/go/src/github.com/traPtitech/traQ/router/middlewares/access_control.go:66 +0x13c
github.com/traPtitech/traQ/router/middlewares.UserAuthenticate.func1.1(0x1486b20, 0xc00b2ebf70, 0x10, 0x1052e60)
	/go/src/github.com/traPtitech/traQ/router/middlewares/user_authenticate.go:81 +0x718
github.com/labstack/echo/v4.(*Echo).add.func1(0x1486b20, 0xc00b2ebf70, 0x1289337, 0x1d)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:509 +0x8a
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x1486b20, 0xc00b2ebf70, 0xc00a42e760, 0xc0053853e0)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.1.14/middleware/cors.go:121 +0x477
github.com/traPtitech/traQ/router/middlewares.RequestCounter.func1.1(0x1486b20, 0xc00b2ebf70, 0x5, 0x1267120)
	/go/src/github.com/traPtitech/traQ/router/middlewares/request_counter.go:19 +0x3d
github.com/traPtitech/traQ/router/extension.Wrap.func1.1(0x1486940, 0xc00a42e6e0, 0xc000d9e290, 0xc00550bba8)
	/go/src/github.com/traPtitech/traQ/router/extension/context.go:51 +0xba
github.com/traPtitech/traQ/router/middlewares.Gzip.func1.1.1(0x1462420, 0xc0033fc7e0, 0xc005491100)
	/go/src/github.com/traPtitech/traQ/router/middlewares/gzip.go:29 +0xa7
net/http.HandlerFunc.ServeHTTP(0xc000d9e260, 0x1462420, 0xc0033fc7e0, 0xc005491100)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x1461e60, 0xc005cf57a0, 0xc005491100)
	/go/pkg/mod/github.com/!n!y!times/gziphandler@v1.1.1/gzip.go:336 +0x211
net/http.HandlerFunc.ServeHTTP(0xc005385380, 0x1461e60, 0xc005cf57a0, 0xc005491100)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/traPtitech/traQ/router/middlewares.Gzip.func1.1(0x1486940, 0xc00a42e6e0, 0x334adaaa, 0x334adaaa0542ef10)
	/go/src/github.com/traPtitech/traQ/router/middlewares/gzip.go:32 +0x115
github.com/traPtitech/traQ/router/middlewares.Recovery.func1.1(0x1486940, 0xc00a42e6e0, 0x0, 0x0)
	/go/src/github.com/traPtitech/traQ/router/middlewares/recovery.go:41 +0x8a
github.com/traPtitech/traQ/router/middlewares.AccessLogging.func2.1(0x1486940, 0xc00a42e6e0, 0xc003e2f8b0, 0xc)
	/go/src/github.com/traPtitech/traQ/router/middlewares/access_logging.go:33 +0x9f
github.com/traPtitech/traQ/router/middlewares.RequestID.func1.1(0x1486940, 0xc00a42e6e0, 0xc003e2f890, 0xe)
	/go/src/github.com/traPtitech/traQ/router/middlewares/request_id.go:13 +0x165
github.com/traPtitech/traQ/router/middlewares.ServerVersion.func1.1(0x1486940, 0xc00a42e6e0, 0x8, 0x8)
	/go/src/github.com/traPtitech/traQ/router/middlewares/server_version.go:13 +0x14b
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000a3c0, 0x1461e60, 0xc005cf57a0, 0xc005491100)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.1.14/echo.go:620 +0x16c
net/http.serverHandler.ServeHTTP(0xc0004ac0e0, 0x1461e60, 0xc005cf57a0, 0xc005491100)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0029e0e60, 0x1466ba0, 0xc00414f700)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
```
https://github.com/traPtitech/traQ/blob/dab20e5f03d987682bfc7d0916bf92e557774a25/router/v3/stamp_palettes.go#L39 で構造体外の変数でバリデーションを行なっているため

**Comment by motoki317** [comment]
これも考えないといけない？
https://github.com/go-ozzo/ozzo-validation#types-implementing-sqlvaluer
https://github.com/traPtitech/traQ/blob/master/model/uuids.go#L12

**Comment by wtks** [comment]
そうですね。それを考えた結果今の感じになって、別のバグ(これ)が発生してます
